name: pyomo-hackathon

dependencies:
  - python >= 3.6
  - glpk
  - matplotlib >= 2.0
  - numpy
  - pandas
  - pyomo
  - pyomo.extras
  - scipy
  - pip:
    - install git+https://github.com/NREL/gdx-pandas.git@v1.0.1
